model_params:
  img_size: 32
  patch_size: 2
  num_channels: 4
  embed_dim: 1024
  depth: 21
  num_heads: 16
  mlp_ratio: 4
  qkv_bias: False
  mlp_time_embed: False
  num_classes: 1000
  normalize_timesteps: True

autoencoder:
  autoencoder_checkpoint_path: ./checkpoints/autoencoder/autoencoder_kl.pth